[env:lilygo-t-embed]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=170
    -DTFT_HEIGHT=320
    -DCGRAM_OFFSET=1       # ВОТ СЕКРЕТ БРЮСА: Смещение сетки экрана
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=13
    -DTFT_RST=9
    -DTFT_BL=15            # Указываем пин подсветки для библиотеки
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
